spring:
  mvc:
    view:
      prefix: /WEB-INF/views/  #경로 설정
      suffix: .jsp             # 파일 확장자 지정

  # html 수정 시 자동 적용
  devtools:
    livereload:
      enabled: true

  application:
    name: glass_time_studio

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: "9wxkTBcDOrxilIhOah5r"
            client-secret: "vkqt29s3Ft"
            scope: name, email, birthday, birthyear, mobile
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원 정보를 json으로 받는데, response 키값으로 네이버가 리턴해줌.

  datasource:
    url: jdbc:postgresql://localhost:5432/glass_time_studio?characterEncoding=UTF-8
#    username: ${PGUSER}
#    password: ${PGPASSWORD}
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
#      엔티티 추가할 경우
      ddl-auto: create
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      write-dates-as-timestamps: false
logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: DEBUG
        orm:
          jpa: DEBUG

jwt:
  key:
    secret: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 1440
  refresh-token-expiration-minutes: 1440

mail:
  address:
    admin: han2041126@gmail.com