spring:
  application:
    name: glass_time_studio

  datasource:
    url: jdbc:postgresql://localhost:5432/glass_time_studio
#    username: ${PGUSER}
#    password: ${PGPASSWORD}
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
#      엔티티 추가할 경우
      ddl-auto: create
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      org:
        springframework:
          orm:
            jpa: DEBUG
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 9wxkTBcDOrxilIhOah5r
            client-secret: vkqt29s3Ft
            scope: name, email, birthday, birthyear, mobile
            authorization-grant-type: authorization_code
            redirect-uri: {baseUrl}/login/oauth2/code/naver
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  jwt:
    key:
      secret: ${JWT_SECRET_KEY}
    access-token-expiration-minutes: 1440
    refresh-token-expiration-minutes: 1440

  mail:
    address:
      admin: han2041126@gmail.com